// app/layout.js

import "./globals.css";
import Navbar from "./components/Navbar/page";
import { geistMono, geistSans, integralCF, satoshi } from "./fonts";
// Import all the font definitions from your new fonts.js file

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    // Apply all font variables to the <html> tag
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${integralCF.variable} ${satoshi.variable}`}
    >
      <body
        className={`antialiased`} // Keep only global body styles here
      >
        <div className="max-w-11/12 mx-auto">
          <Navbar></Navbar>
        </div>
        {children}
      </body>
    </html>
  );
}
